"""Node identity, short-lived capabilities, and remote tunnel lifecycle.

The manager imports the stream mux lazily; it is not re-exported here.
"""

from __future__ import annotations

from nerdit.core.link.capability import MintedCapability, mint_capability
from nerdit.core.link.client import (
    ENTITLEMENT_ERROR_CODES,
    HANDSHAKE_TIMEOUT_S,
    CloseClass,
    CloseInfo,
    Connector,
    DialRejected,
    HandshakeResult,
    InboundStreamHandler,
    LinkClosedError,
    LinkConnection,
    LinkHandshakeError,
    LinkSocket,
    MuxContext,
    classify_close,
    dial_relay,
    dial_url,
)
from nerdit.core.link.frames import (
    ERROR_CODE_AUTH,
    ERROR_CODE_INTERNAL,
    PROTOCOL_VERSION,
    CloseStream,
    Downlink,
    ErrorFrame,
    FrameError,
    HelloAck,
    NodeChallenge,
    OpenStream,
    StreamBody,
    StreamDownlink,
    StreamEnd,
    StreamLimits,
    decode_body,
    dump_frame,
    encode_body,
    heartbeat_frame,
    hello_frame,
    is_forwardable_path,
    parse_downlink,
    response_body_frame,
    response_end_frame,
    response_head_frame,
    stream_error_frame,
)
from nerdit.core.link.identity import (
    ED25519_REFERENCE_PREFIX,
    LinkIdentityError,
    NodeIdentity,
    credential_fingerprint,
    load_or_create_identity,
    proof_message,
    public_reference,
    resolve_key_file,
    sign_node_proof,
    valid_public_reference,
    verify_node_proof,
)
from nerdit.core.link.manager import (
    AUTH_FAILURE_LIMIT,
    DISCONNECT_REASONS,
    DISPLACED_RETRY_DELAY_S,
    LinkManager,
    LinkStatus,
)

__all__ = [
    "AUTH_FAILURE_LIMIT",
    "DISCONNECT_REASONS",
    "DISPLACED_RETRY_DELAY_S",
    "ED25519_REFERENCE_PREFIX",
    "ENTITLEMENT_ERROR_CODES",
    "ERROR_CODE_AUTH",
    "ERROR_CODE_INTERNAL",
    "HANDSHAKE_TIMEOUT_S",
    "PROTOCOL_VERSION",
    "CloseClass",
    "CloseInfo",
    "CloseStream",
    "Connector",
    "DialRejected",
    "Downlink",
    "ErrorFrame",
    "FrameError",
    "HandshakeResult",
    "HelloAck",
    "InboundStreamHandler",
    "LinkClosedError",
    "LinkConnection",
    "LinkHandshakeError",
    "LinkIdentityError",
    "LinkManager",
    "LinkSocket",
    "LinkStatus",
    "MintedCapability",
    "MuxContext",
    "NodeChallenge",
    "NodeIdentity",
    "OpenStream",
    "StreamBody",
    "StreamDownlink",
    "StreamEnd",
    "StreamLimits",
    "classify_close",
    "credential_fingerprint",
    "decode_body",
    "dial_relay",
    "dial_url",
    "dump_frame",
    "encode_body",
    "heartbeat_frame",
    "hello_frame",
    "is_forwardable_path",
    "load_or_create_identity",
    "mint_capability",
    "parse_downlink",
    "proof_message",
    "public_reference",
    "resolve_key_file",
    "response_body_frame",
    "response_end_frame",
    "response_head_frame",
    "sign_node_proof",
    "stream_error_frame",
    "valid_public_reference",
    "verify_node_proof",
]
