"""OpenAPI curation drift guard (P6 / D4).

Asserts the schema stays agent-consumable: every documented operation carries a
tag and a stable, explicit, unique ``operationId`` (generated clients pin to
these ids — a rename or a fallback to FastAPI's autogenerated
``handlername_path_method`` id is a breaking change).

``app.openapi()`` is sync, so no TestClient (and no aiosqlite lifespan) is
needed here.
"""

from __future__ import annotations

import re

import pytest
from fastapi import FastAPI
from fastapi.routing import APIRoute
from fastapi.utils import generate_unique_id

from nerdit.daemon.server import create_app

# Explicit ids are snake_case verb-noun identifiers.
_SNAKE_CASE = re.compile(r"^[a-z][a-z0-9_]*$")

# The curated tag set applied at include time in server.py.
_EXPECTED_TAGS = {
    "Health",
    "Auth",
    "GPUs",
    "Cluster",
    "Events",
    "Images",
    "Audit",
    "Config",
    "Tokens",
    "Services",
    "Deploy",
    "Secrets",
    "Models",
    "Databases",
    "Proxy",
    "Store",
    "System",
    "Link",
    "Workspaces",
    # (P26 WP-H) The hosted-share trio. Its own tag rather than a fold into
    # Services: exposure is the surface custom domains (WP1) and ACME (WP2)
    # will join, so a generated client finds all of it under one heading.
    "Exposure",
    # (P40b / D-P40-10) The project noun, one tag, registered last.
    "Projects",
}


@pytest.fixture(scope="module")
def app() -> FastAPI:
    return create_app()


@pytest.fixture(scope="module")
def schema(app: FastAPI) -> dict:
    return app.openapi()


def _documented_routes(app: FastAPI) -> list[APIRoute]:
    """Every APIRoute that ends up in the OpenAPI schema."""
    return [r for r in app.routes if isinstance(r, APIRoute) and r.include_in_schema]


def _operations(schema: dict):
    """Yield (path, method, operation-object) for every documented operation."""
    for path, methods in schema.get("paths", {}).items():
        for method, operation in methods.items():
            if method in {"get", "put", "post", "delete", "patch"}:
                yield path, method, operation


def test_every_documented_route_has_an_explicit_operation_id(app: FastAPI) -> None:
    """Every schema-visible route declares ``operation_id=`` (never the default)."""
    missing = [
        f"{sorted(route.methods)} {route.path}"
        for route in _documented_routes(app)
        if route.operation_id is None
    ]
    assert not missing, f"Routes without an explicit operation_id: {missing}"


def test_operation_ids_are_not_fastapi_defaults(app: FastAPI) -> None:
    """No explicit id may collide with FastAPI's autogenerated fallback shape."""
    defaults = [
        f"{route.path}: {route.operation_id}"
        for route in _documented_routes(app)
        if route.operation_id == generate_unique_id(route)
    ]
    assert not defaults, f"Routes carrying a default-looking operationId: {defaults}"


def test_operation_ids_are_unique_and_snake_case(schema: dict) -> None:
    seen: dict[str, str] = {}
    for path, method, operation in _operations(schema):
        op_id = operation.get("operationId")
        location = f"{method.upper()} {path}"
        assert op_id, f"{location} has no operationId"
        assert _SNAKE_CASE.match(op_id), f"{location}: operationId '{op_id}' is not snake_case"
        assert op_id not in seen, (
            f"operationId '{op_id}' duplicated on {seen[op_id]} and {location}"
        )
        seen[op_id] = location


def test_every_operation_has_a_curated_tag(schema: dict) -> None:
    for path, method, operation in _operations(schema):
        location = f"{method.upper()} {path}"
        tags = operation.get("tags")
        assert tags, f"{location} has no tags"
        unknown = set(tags) - _EXPECTED_TAGS
        assert not unknown, f"{location} carries uncurated tags: {sorted(unknown)}"


def test_p7_config_operation_ids_are_present(schema: dict) -> None:
    """The P7 config surface keeps its pinned operationIds (rename protection).

    Generated clients and the MCP tools pin to these ids; a rename is a
    breaking change even if the paths survive.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"apply_daemon_config", "get_app_config", "put_app_config_section"}
    missing = expected - op_ids
    assert not missing, f"P7 config operationIds missing from the schema: {sorted(missing)}"


def test_p15_operation_ids_are_present(schema: dict) -> None:
    """The P15 managed-data surface keeps its pinned operationIds (rename protection)."""
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"create_database", "list_databases", "create_volume_backup"}
    missing = expected - op_ids
    assert not missing, f"P15 database operationIds missing from the schema: {sorted(missing)}"


def test_p8_secrets_operation_ids_are_present(schema: dict) -> None:
    """The P8 secrets surface keeps its pinned operationIds (rename protection)."""
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {
        "rotate_secrets_key",
        "set_service_secrets",
        "list_secret_names",
        "delete_service_secret",
        "delete_service_secrets",
    }
    missing = expected - op_ids
    assert not missing, f"P8 secrets operationIds missing from the schema: {sorted(missing)}"


def test_p13a_operation_ids_are_present(schema: dict) -> None:
    """The P13a service-diagnostics surface keeps its pinned operationIds.

    §1.13 pins seven P13 ids; five (`converge_service` etc.) are P13b/c and
    cannot land yet, so this pins only the two shipped in P13a. Generated
    clients and the MCP tools pin to these ids; a rename is a breaking change
    even if the paths survive.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"wait_for_service", "diagnose_service"}
    missing = expected - op_ids
    assert not missing, f"P13a operationIds missing from the schema: {sorted(missing)}"


def test_p13b_wp7_operation_ids_are_present(schema: dict) -> None:
    """The P13b WP7 proxy-observability surface keeps its pinned operationIds.

    §1.13 pins these under the Proxy tag; generated clients / MCP tools pin to
    them, so a rename is a breaking change even if the paths survive.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"get_proxy_status", "list_routes"}
    missing = expected - op_ids
    assert not missing, f"P13b WP7 operationIds missing from the schema: {sorted(missing)}"


def test_p13b_wp6_operation_ids_are_present(schema: dict) -> None:
    """The P13b WP6 system surface keeps its pinned operationIds.

    §1.13 pins these under the new System tag; generated clients / MCP tools pin
    to them, so a rename is a breaking change even if the paths survive. Taken
    together with the P13a + WP7 pins, all seven P13 §1.13 ids are covered.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"get_capabilities", "get_doctor", "restart_daemon"}
    missing = expected - op_ids
    assert not missing, f"P13b WP6 operationIds missing from the schema: {sorted(missing)}"


def test_p14b_operation_ids_are_present(schema: dict) -> None:
    """The P14b WP-A2 disk/GC surface keeps its pinned operationIds.

    Generated clients / MCP tools pin to these, so a rename is a breaking change
    even if the paths survive. Both live under the existing System tag.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"get_system_disk", "run_system_gc"}
    missing = expected - op_ids
    assert not missing, f"P14b operationIds missing from the schema: {sorted(missing)}"


def test_p14c_operation_ids_are_present(schema: dict) -> None:
    """The P14c WP-B3 backup route keeps its pinned operationId.

    Generated clients / MCP tools pin to this, so a rename is a breaking change
    even if the path survives. It lives under the existing System tag (no
    ``_EXPECTED_TAGS`` edit).
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"create_backup"}
    missing = expected - op_ids
    assert not missing, f"P14c operationIds missing from the schema: {sorted(missing)}"


def test_p20_operation_ids_are_present(schema: dict) -> None:
    """The P20 one-off run route keeps its pinned operationId.

    Generated clients / the MCP ``run_command`` tool pin to this, so a rename is
    a breaking change even if the path survives. It lives under the existing
    Services tag (declared on the route decorator — the include in
    ``routes/services.py`` is bare — so no ``_EXPECTED_TAGS`` edit).
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"run_service_command"}
    missing = expected - op_ids
    assert not missing, f"P20 operationIds missing from the schema: {sorted(missing)}"


def test_p24_wp4_operation_ids_are_present(schema: dict) -> None:
    """The P24 WP4 per-service stats route keeps its pinned operationId.

    Generated clients / the MCP ``service_stats`` tool pin to this, so a rename
    is a breaking change even if the path survives. It lives under the existing
    Services tag (declared on the route decorator — the include in
    ``routes/services.py`` is bare — so no ``_EXPECTED_TAGS`` edit).
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"get_service_stats"}
    missing = expected - op_ids
    assert not missing, f"P24 WP4 operationIds missing from the schema: {sorted(missing)}"


def test_p24_wp3_operation_ids_are_present(schema: dict) -> None:
    """The P24 WP3 log stream keeps its pinned operationId.

    Generated clients and the dashboard's follow view pin to it, so a rename is
    a breaking change even if the path survives. It lives under the existing
    Services tag (declared on the route decorator — the include in
    ``routes/services.py`` is bare — so no ``_EXPECTED_TAGS`` edit).
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"stream_service_logs"}
    missing = expected - op_ids
    assert not missing, f"P24 WP3 operationIds missing from the schema: {sorted(missing)}"


def test_service_logs_filters_are_documented_as_literal(schema: dict) -> None:
    """``grep`` is a substring, and the schema an agent reads must say so (WP3.2).

    The bug class this pins: an agent reads "grep", assumes a regex, sends
    ``Traceback.*Error``, gets zero rows back, and concludes the service logged
    nothing. Both the paged read and the stream must carry the same wording.
    """
    for path in ("/api/services/{ident}/logs", "/api/services/{ident}/logs/stream"):
        params = {
            p["name"]: p.get("description", "").lower()
            for p in schema["paths"][path]["get"]["parameters"]
        }
        assert "not a regex" in params["grep"], path
        assert "iso-8601" in params["since"], path


def test_p24_wp2_operation_ids_are_present(schema: dict) -> None:
    """The P24 WP2 event feed keeps its pinned operationIds.

    ``list_events`` is new; ``stream_cluster_events`` is the *existing* stream
    id, pinned here because WP2 rewrote that route to add durable resume — the
    id must survive the rewrite (generated clients and the dashboard's
    fetch-streaming consumer pin to it). Both live under the existing Events
    tag, so no ``_EXPECTED_TAGS`` edit.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"list_events", "stream_cluster_events"}
    missing = expected - op_ids
    assert not missing, f"P24 WP2 operationIds missing from the schema: {sorted(missing)}"


def test_list_events_documents_both_pagination_directions(schema: dict) -> None:
    """The two modes are a contract, not an implementation detail (WP2.1).

    The bug class this pins: a consumer told to "reconcile" reaches for
    ``cursor``, which walks **backwards** into history, and silently never sees
    the events it was reconciling toward. The direction of each param must be
    stated in the schema an agent reads.
    """
    params = schema["paths"]["/api/events"]["get"]["parameters"]
    described = {p["name"]: p.get("description", "").lower() for p in params}
    assert "cursor browses backwards, id desc" in described["cursor"]
    assert "since_id replays forwards, id asc" in described["since_id"]


def test_p25_operation_ids_are_present(schema: dict) -> None:
    """Pin self-service token operation IDs and the explicit API operation count.

    Generated clients and token whoami/rotate depend on these IDs. Update the
    count deliberately when adding routes so accidental exposure fails this test.
    Pre-auth uses the existing claim operation; it adds no route. Database
    dump/list/restore bring the total to 82 operations; the P40b project
    quartet takes it to 86; the P40c variable quartet to 90; P40d's
    ``apply_project`` to 91; P41b's discovery and address binding to 93;
    P41d's project logs and diagnosis to 95; P41e's rename to 96.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"get_self_token", "rotate_self_token"}
    missing = expected - op_ids
    assert not missing, f"P25 operationIds missing from the schema: {sorted(missing)}"
    assert {"get_link_project", "push_link_public_address"} <= op_ids
    assert {"project_logs", "diagnose_project"} <= op_ids
    assert "rename_project" in op_ids
    assert len(op_ids) == 96


def test_p40b_operation_ids_are_present(schema: dict) -> None:
    """The P40b project quartet keeps its pinned operationIds (D-P40-10).

    ``nerdit projects …`` and the four MCP tools pin to these; all four live
    under the new ``Projects`` tag, registered last.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"create_project", "list_projects", "get_project", "delete_project"}
    missing = expected - op_ids
    assert not missing, f"P40b operationIds missing from the schema: {sorted(missing)}"


def test_p40c_operation_ids_are_present(schema: dict) -> None:
    """The P40c variable quartet keeps its pinned operationIds, under `Projects` (D-P40-10)."""
    ops = {op.get("operationId"): op for _, _, op in _operations(schema)}
    expected = {"list_variables", "set_variables", "delete_variable", "resolve_variables"}
    assert not expected - ops.keys()
    assert all(ops[op_id]["tags"] == ["Projects"] for op_id in expected)


def test_p40d_apply_operation_is_multipart_under_projects(schema: dict) -> None:
    """`apply_project` sits under `Projects` and takes the archive-or-git multipart form."""
    op = schema["paths"]["/api/projects/{project}/apply"]["post"]
    assert op["operationId"] == "apply_project" and op["tags"] == ["Projects"]
    assert list(op["requestBody"]["content"]) == ["multipart/form-data"]
    assert [p["name"] for p in op["parameters"]] == ["project", "dry_run"]


def test_p37_operation_ids_are_present(schema: dict) -> None:
    """The P37 dump trio keeps its pinned operationIds (§1.4).

    Generated clients, ``nerdit db dump|dumps|restore`` and the two MCP tools
    all pin to these, so a rename is a breaking change even though the paths
    would survive it. All three live under the existing ``Databases`` tag — the
    surface is database-shaped, not a second backup surface — so no
    ``_EXPECTED_TAGS`` edit.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {"create_database_dump", "list_database_dumps", "restore_database_dump"}
    missing = expected - op_ids
    assert not missing, f"P37 operationIds missing from the schema: {sorted(missing)}"


def test_p29_operation_ids_are_present(schema: dict) -> None:
    """The P29 agent-workspace quartet keeps its pinned operationIds.

    ``deploy_workspace`` is deliberately distinct from the pre-existing
    ``deploy_app`` operationId on ``POST /deploy`` — the MCP tool named
    ``deploy_app`` projects THIS route, and the two namespaces are separate by
    decision (plan §2). A rename here breaks generated clients.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {
        "write_workspace_files",
        "get_workspace",
        "read_workspace_file",
        "deploy_workspace",
    }
    missing = expected - op_ids
    assert not missing, f"P29 operationIds missing from the schema: {sorted(missing)}"


def test_p26_operation_ids_are_present(schema: dict) -> None:
    """The P26 WP-H exposure surface keeps its pinned operationIds.

    Three share operations under the new ``Exposure`` tag plus ``refresh_link``,
    which stays on the existing ``Link`` tag — it is a link-custody op (it
    commits ``[link]`` config under the same admin gate and mutation lock as the
    claim), not an exposure one, and a generated client should find it beside
    ``claim_link``.
    """
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    expected = {
        "get_share",
        "set_share",
        "remove_share",
        "refresh_link",
        "list_domains",
        "add_domain",
        "remove_domain",
    }
    missing = expected - op_ids
    assert not missing, f"P26 operationIds missing from the schema: {sorted(missing)}"

    paths = schema["paths"]
    share_ops = paths["/api/services/{name}/share"]
    assert set(share_ops) == {"get", "put", "delete"}
    # The share trio is Exposure; refresh is Link. Getting this backwards would
    # scatter the surface across two headings in every generated client.
    for method in ("get", "put", "delete"):
        assert share_ops[method]["tags"] == ["Exposure"]
    assert paths["/api/link/refresh"]["post"]["tags"] == ["Link"]
    # ``/api`` only, like the link and workspace surfaces — no bare-root alias.
    assert "/services/{name}/share" not in paths
    assert "/link/refresh" not in paths


def test_p26_wp1_domain_operations_are_present(schema: dict) -> None:
    """(P26 WP1) The custom-domain trio joins the SAME ``Exposure`` tag.

    Split across two paths on purpose (S-W2): the domain is the resource id, so
    the collection lists and the item is bound/released. Both are ``/api``-only,
    like the share trio they sit beside.
    """
    paths = schema["paths"]
    collection = paths["/api/services/{name}/domains"]
    item = paths["/api/services/{name}/domains/{domain}"]
    assert set(collection) == {"get"}
    assert set(item) == {"put", "delete"}
    assert collection["get"]["operationId"] == "list_domains"
    assert item["put"]["operationId"] == "add_domain"
    assert item["delete"]["operationId"] == "remove_domain"
    for op in (collection["get"], item["put"], item["delete"]):
        assert op["tags"] == ["Exposure"]
    assert "/services/{name}/domains" not in paths
    assert "/services/{name}/domains/{domain}" not in paths


def test_legacy_bare_root_aliases_are_hidden_from_the_schema(schema: dict) -> None:
    """The legacy v0.2 root mounts stay functional but undocumented.

    They alias the /api/* operations handler-for-handler; documenting both would
    duplicate every operationId (invalid OpenAPI).
    """
    paths = set(schema.get("paths", {}))
    assert "/api/health" in paths
    assert "/api/gpus" in paths
    assert "/health" not in paths
    assert "/gpus" not in paths


# The 19 operationIds retired with the batch HTTP surface (simplification WP2).
# They are a removed public contract: re-adding one under the same id would
# silently resurrect a route agents were told is gone.
_REMOVED_BATCH_OPERATION_IDS = {
    "create_job",
    "upload_job",
    "list_jobs",
    "list_jobs_history",
    "get_job",
    "stop_job",
    "update_job_priority",
    "pause_job",
    "resume_job",
    "get_job_logs",
    "stream_job_logs",
    "cleanup_jobs",
    "reorder_queue",
    "list_templates",
    "get_template",
    "list_files",
    "download_file",
    "upload_file",
    "delete_upload",
}


def test_batch_operation_ids_are_gone(schema: dict) -> None:
    """The batch/queue/templates/files operations left the schema for good."""
    op_ids = {op.get("operationId") for _, _, op in _operations(schema)}
    resurrected = op_ids & _REMOVED_BATCH_OPERATION_IDS
    assert not resurrected, f"Removed batch operationIds are back: {sorted(resurrected)}"
